name: "sdl"
on: [push]
jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: |
          zig build ci --summary all
      - if: ${{ matrix.os == 'ubuntu-latest'  }}
        uses: actions/upload-artifact@v4
        with:
          name: breakout-archives
          path: |
            zig-out/x86_64-windows/unzip.exe
            zig-out/x86_64-windows/unzip.pdb
            zig-out/aarch64-windows/unzip.exe
            zig-out/aarch64-windows/unzip.exe
            zig-out/breakout-x86_64-linux.tar.gz
            zig-out/breakout-x86_64-macos.tar.gz
            zig-out/breakout-x86_64-windows.zip
            zig-out/breakout-aarch64-linux.tar.gz
            zig-out/breakout-aarch64-macos.tar.gz
            zig-out/breakout-aarch64-windows.zip
            zig-out/breakout-arm-linux.tar.gz
            zig-out/breakout-riscv64-linux.tar.gz
            zig-out/breakout-powerpc-linux.tar.gz
            zig-out/breakout-powerpc64le-linux.tar.gz
